// -------------------------------------------------------------
//
// Module: filter_assgn_3
// Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
// Generated on: 2022-06-20 19:38:06
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: D:\Ruhma_work
// Name: filter_assgn_3
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate            : N/A (normalized frequency)
// Response               : Bandpass
// Specification          : Fst1,Fp1,Fp2,Fst2,Ast1,Ap,Ast2
// Second Stopband Atten. : 50 dB
// Second Stopband Edge   : 0.5
// First Passband Edge    : 0.25
// Second Passband Edge   : 0.375
// First Stopband Edge    : 0.125
// First Stopband Atten.  : 50 dB
// Passband Ripple        : 1 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 4
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s16,14 -> [-2 2)
// Denominator         : s16,14 -> [-2 2)
// Scale Values        : s16,15 -> [-1 1)
// Input               : s16,15 -> [-1 1)
// Section Input       : s16,12 -> [-8 8)
// Section Output      : s16,13 -> [-4 4)
// Output              : s32,29 -> [-4 4)
// State               : s16,15 -> [-1 1)
// Numerator Prod      : s31,31 -> [-5.000000e-01 5.000000e-01)
// Denominator Prod    : s31,30 -> [-1 1)
// Numerator Accum     : s34,31 -> [-4 4)
// Denominator Accum   : s34,30 -> [-8 8)
// Round Mode          : convergent
// Overflow Mode       : wrap
// Cast Before Sum     : true
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module filter_assgn_3
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [31:0] filter_out; //sfix32_En29

////////////////////////////////////////////////////////////////
//Module Architecture: filter_assgn_3
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] scaleconst1 = 16'b0100101011101100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section1 = 16'b0010100000111100; //sfix16_En14
  parameter signed [15:0] coeff_b3_section1 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section1 = 16'b1100010111000001; //sfix16_En14
  parameter signed [15:0] coeff_a3_section1 = 16'b0011011100110010; //sfix16_En14
  parameter signed [15:0] scaleconst2 = 16'b0100101011101100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section2 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section2 = 16'b1000100111010110; //sfix16_En14
  parameter signed [15:0] coeff_b3_section2 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section2 = 16'b1011001110101100; //sfix16_En14
  parameter signed [15:0] coeff_a3_section2 = 16'b0011100000100101; //sfix16_En14
  parameter signed [15:0] scaleconst3 = 16'b0001000000101100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section3 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section3 = 16'b1110101011000111; //sfix16_En14
  parameter signed [15:0] coeff_b3_section3 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section3 = 16'b1101000000000010; //sfix16_En14
  parameter signed [15:0] coeff_a3_section3 = 16'b0011110011000101; //sfix16_En14
  parameter signed [15:0] scaleconst4 = 16'b0001000000101100; //sfix16_En15
  parameter signed [15:0] coeff_b1_section4 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_b2_section4 = 16'b1001100011000001; //sfix16_En14
  parameter signed [15:0] coeff_b3_section4 = 16'b0100000000000000; //sfix16_En14
  parameter signed [15:0] coeff_a2_section4 = 16'b1010011101100110; //sfix16_En14
  parameter signed [15:0] coeff_a3_section4 = 16'b0011110110000010; //sfix16_En14
  // Signals
  reg  signed [15:0] input_register; // sfix16_En15
  wire signed [33:0] scale1; // sfix34_En30
  wire signed [31:0] mul_temp; // sfix32_En30
  wire signed [15:0] scaletypeconvert1; // sfix16_En12
  // Section 1 Signals 
  wire signed [33:0] a1sum1; // sfix34_En30
  wire signed [33:0] a2sum1; // sfix34_En30
  wire signed [33:0] b1sum1; // sfix34_En31
  wire signed [33:0] b2sum1; // sfix34_En31
  wire signed [15:0] typeconvert1; // sfix16_En15
  reg  signed [15:0] delay_section1 [0:1] ; // sfix16_En15
  wire signed [33:0] inputconv1; // sfix34_En30
  wire signed [30:0] a2mul1; // sfix31_En30
  wire signed [30:0] a3mul1; // sfix31_En30
  wire signed [30:0] b1mul1; // sfix31_En31
  wire signed [30:0] b2mul1; // sfix31_En31
  wire signed [30:0] b3mul1; // sfix31_En31
  wire signed [31:0] mul_temp_1; // sfix32_En29
  wire signed [31:0] mul_temp_2; // sfix32_En29
  wire signed [31:0] mul_temp_3; // sfix32_En29
  wire signed [33:0] sub_cast; // sfix34_En30
  wire signed [33:0] sub_cast_1; // sfix34_En30
  wire signed [34:0] sub_temp; // sfix35_En30
  wire signed [33:0] sub_cast_2; // sfix34_En30
  wire signed [33:0] sub_cast_3; // sfix34_En30
  wire signed [34:0] sub_temp_1; // sfix35_En30
  wire signed [33:0] b1multypeconvert1; // sfix34_En31
  wire signed [33:0] add_cast; // sfix34_En31
  wire signed [33:0] add_cast_1; // sfix34_En31
  wire signed [34:0] add_temp; // sfix35_En31
  wire signed [33:0] add_cast_2; // sfix34_En31
  wire signed [33:0] add_cast_3; // sfix34_En31
  wire signed [34:0] add_temp_1; // sfix35_En31
  wire signed [15:0] section_result1; // sfix16_En13
  wire signed [33:0] scale2; // sfix34_En30
  wire signed [31:0] mul_temp_4; // sfix32_En28
  wire signed [15:0] scaletypeconvert2; // sfix16_En12
  // Section 2 Signals 
  wire signed [33:0] a1sum2; // sfix34_En30
  wire signed [33:0] a2sum2; // sfix34_En30
  wire signed [33:0] b1sum2; // sfix34_En31
  wire signed [33:0] b2sum2; // sfix34_En31
  wire signed [15:0] typeconvert2; // sfix16_En15
  reg  signed [15:0] delay_section2 [0:1] ; // sfix16_En15
  wire signed [33:0] inputconv2; // sfix34_En30
  wire signed [30:0] a2mul2; // sfix31_En30
  wire signed [30:0] a3mul2; // sfix31_En30
  wire signed [30:0] b1mul2; // sfix31_En31
  wire signed [30:0] b2mul2; // sfix31_En31
  wire signed [30:0] b3mul2; // sfix31_En31
  wire signed [31:0] mul_temp_5; // sfix32_En29
  wire signed [31:0] mul_temp_6; // sfix32_En29
  wire signed [31:0] mul_temp_7; // sfix32_En29
  wire signed [33:0] sub_cast_4; // sfix34_En30
  wire signed [33:0] sub_cast_5; // sfix34_En30
  wire signed [34:0] sub_temp_2; // sfix35_En30
  wire signed [33:0] sub_cast_6; // sfix34_En30
  wire signed [33:0] sub_cast_7; // sfix34_En30
  wire signed [34:0] sub_temp_3; // sfix35_En30
  wire signed [33:0] b1multypeconvert2; // sfix34_En31
  wire signed [33:0] add_cast_4; // sfix34_En31
  wire signed [33:0] add_cast_5; // sfix34_En31
  wire signed [34:0] add_temp_2; // sfix35_En31
  wire signed [33:0] add_cast_6; // sfix34_En31
  wire signed [33:0] add_cast_7; // sfix34_En31
  wire signed [34:0] add_temp_3; // sfix35_En31
  wire signed [15:0] section_result2; // sfix16_En13
  wire signed [33:0] scale3; // sfix34_En30
  wire signed [31:0] mul_temp_8; // sfix32_En28
  wire signed [15:0] scaletypeconvert3; // sfix16_En12
  // Section 3 Signals 
  wire signed [33:0] a1sum3; // sfix34_En30
  wire signed [33:0] a2sum3; // sfix34_En30
  wire signed [33:0] b1sum3; // sfix34_En31
  wire signed [33:0] b2sum3; // sfix34_En31
  wire signed [15:0] typeconvert3; // sfix16_En15
  reg  signed [15:0] delay_section3 [0:1] ; // sfix16_En15
  wire signed [33:0] inputconv3; // sfix34_En30
  wire signed [30:0] a2mul3; // sfix31_En30
  wire signed [30:0] a3mul3; // sfix31_En30
  wire signed [30:0] b1mul3; // sfix31_En31
  wire signed [30:0] b2mul3; // sfix31_En31
  wire signed [30:0] b3mul3; // sfix31_En31
  wire signed [31:0] mul_temp_9; // sfix32_En29
  wire signed [31:0] mul_temp_10; // sfix32_En29
  wire signed [31:0] mul_temp_11; // sfix32_En29
  wire signed [33:0] sub_cast_8; // sfix34_En30
  wire signed [33:0] sub_cast_9; // sfix34_En30
  wire signed [34:0] sub_temp_4; // sfix35_En30
  wire signed [33:0] sub_cast_10; // sfix34_En30
  wire signed [33:0] sub_cast_11; // sfix34_En30
  wire signed [34:0] sub_temp_5; // sfix35_En30
  wire signed [33:0] b1multypeconvert3; // sfix34_En31
  wire signed [33:0] add_cast_8; // sfix34_En31
  wire signed [33:0] add_cast_9; // sfix34_En31
  wire signed [34:0] add_temp_4; // sfix35_En31
  wire signed [33:0] add_cast_10; // sfix34_En31
  wire signed [33:0] add_cast_11; // sfix34_En31
  wire signed [34:0] add_temp_5; // sfix35_En31
  wire signed [15:0] section_result3; // sfix16_En13
  wire signed [33:0] scale4; // sfix34_En30
  wire signed [31:0] mul_temp_12; // sfix32_En28
  wire signed [15:0] scaletypeconvert4; // sfix16_En12
  // Section 4 Signals 
  wire signed [33:0] a1sum4; // sfix34_En30
  wire signed [33:0] a2sum4; // sfix34_En30
  wire signed [33:0] b1sum4; // sfix34_En31
  wire signed [33:0] b2sum4; // sfix34_En31
  wire signed [15:0] typeconvert4; // sfix16_En15
  reg  signed [15:0] delay_section4 [0:1] ; // sfix16_En15
  wire signed [33:0] inputconv4; // sfix34_En30
  wire signed [30:0] a2mul4; // sfix31_En30
  wire signed [30:0] a3mul4; // sfix31_En30
  wire signed [30:0] b1mul4; // sfix31_En31
  wire signed [30:0] b2mul4; // sfix31_En31
  wire signed [30:0] b3mul4; // sfix31_En31
  wire signed [31:0] mul_temp_13; // sfix32_En29
  wire signed [31:0] mul_temp_14; // sfix32_En29
  wire signed [31:0] mul_temp_15; // sfix32_En29
  wire signed [33:0] sub_cast_12; // sfix34_En30
  wire signed [33:0] sub_cast_13; // sfix34_En30
  wire signed [34:0] sub_temp_6; // sfix35_En30
  wire signed [33:0] sub_cast_14; // sfix34_En30
  wire signed [33:0] sub_cast_15; // sfix34_En30
  wire signed [34:0] sub_temp_7; // sfix35_En30
  wire signed [33:0] b1multypeconvert4; // sfix34_En31
  wire signed [33:0] add_cast_12; // sfix34_En31
  wire signed [33:0] add_cast_13; // sfix34_En31
  wire signed [34:0] add_temp_6; // sfix35_En31
  wire signed [33:0] add_cast_14; // sfix34_En31
  wire signed [33:0] add_cast_15; // sfix34_En31
  wire signed [34:0] add_temp_7; // sfix35_En31
  wire signed [31:0] output_typeconvert; // sfix32_En29
  reg  signed [31:0] output_register; // sfix32_En29

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign mul_temp = input_register * scaleconst1;
  assign scale1 = $signed({{2{mul_temp[31]}}, mul_temp});

  assign scaletypeconvert1 = (scale1[33:0] + {scale1[18], {17{~scale1[18]}}})>>>18;

  //   ------------------ Section 1 ------------------

  assign typeconvert1 = (a1sum1[30:0] + {a1sum1[15], {14{~a1sum1[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1[0] <= 16'b0000000000000000;
        delay_section1[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= typeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1[15:0], 18'b000000000000000000});

  assign mul_temp_1 = delay_section1[0] * coeff_a2_section1;
  assign a2mul1 = $signed({mul_temp_1[29:0], 1'b0});

  assign mul_temp_2 = delay_section1[1] * coeff_a3_section1;
  assign a3mul1 = $signed({mul_temp_2[29:0], 1'b0});

  assign b1mul1 = $signed({typeconvert1[14:0], 16'b0000000000000000});

  assign mul_temp_3 = delay_section1[0] * coeff_b2_section1;
  assign b2mul1 = $signed({mul_temp_3[28:0], 2'b00});

  assign b3mul1 = $signed({delay_section1[1][14:0], 16'b0000000000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{3{a2mul1[30]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a2sum1 = sub_temp[33:0];

  assign sub_cast_2 = a2sum1;
  assign sub_cast_3 = $signed({{3{a3mul1[30]}}, a3mul1});
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign a1sum1 = sub_temp_1[33:0];

  assign b1multypeconvert1 = $signed({{3{b1mul1[30]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{3{b2mul1[30]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b2sum1 = add_temp[33:0];

  assign add_cast_2 = b2sum1;
  assign add_cast_3 = $signed({{3{b3mul1[30]}}, b3mul1});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign b1sum1 = add_temp_1[33:0];

  assign section_result1 = (b1sum1[33:0] + {b1sum1[18], {17{~b1sum1[18]}}})>>>18;

  assign mul_temp_4 = section_result1 * scaleconst2;
  assign scale2 = $signed({mul_temp_4[31:0], 2'b00});

  assign scaletypeconvert2 = (scale2[33:0] + {scale2[18], {17{~scale2[18]}}})>>>18;

  //   ------------------ Section 2 ------------------

  assign typeconvert2 = (a1sum2[30:0] + {a1sum2[15], {14{~a1sum2[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section2
      if (reset == 1'b1) begin
        delay_section2[0] <= 16'b0000000000000000;
        delay_section2[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section2[1] <= delay_section2[0];
          delay_section2[0] <= typeconvert2;
        end
      end
    end // delay_process_section2

  assign inputconv2 = $signed({scaletypeconvert2[15:0], 18'b000000000000000000});

  assign mul_temp_5 = delay_section2[0] * coeff_a2_section2;
  assign a2mul2 = $signed({mul_temp_5[29:0], 1'b0});

  assign mul_temp_6 = delay_section2[1] * coeff_a3_section2;
  assign a3mul2 = $signed({mul_temp_6[29:0], 1'b0});

  assign b1mul2 = $signed({typeconvert2[14:0], 16'b0000000000000000});

  assign mul_temp_7 = delay_section2[0] * coeff_b2_section2;
  assign b2mul2 = $signed({mul_temp_7[28:0], 2'b00});

  assign b3mul2 = $signed({delay_section2[1][14:0], 16'b0000000000000000});

  assign sub_cast_4 = inputconv2;
  assign sub_cast_5 = $signed({{3{a2mul2[30]}}, a2mul2});
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign a2sum2 = sub_temp_2[33:0];

  assign sub_cast_6 = a2sum2;
  assign sub_cast_7 = $signed({{3{a3mul2[30]}}, a3mul2});
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign a1sum2 = sub_temp_3[33:0];

  assign b1multypeconvert2 = $signed({{3{b1mul2[30]}}, b1mul2});

  assign add_cast_4 = b1multypeconvert2;
  assign add_cast_5 = $signed({{3{b2mul2[30]}}, b2mul2});
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign b2sum2 = add_temp_2[33:0];

  assign add_cast_6 = b2sum2;
  assign add_cast_7 = $signed({{3{b3mul2[30]}}, b3mul2});
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign b1sum2 = add_temp_3[33:0];

  assign section_result2 = (b1sum2[33:0] + {b1sum2[18], {17{~b1sum2[18]}}})>>>18;

  assign mul_temp_8 = section_result2 * scaleconst3;
  assign scale3 = $signed({mul_temp_8[31:0], 2'b00});

  assign scaletypeconvert3 = (scale3[33:0] + {scale3[18], {17{~scale3[18]}}})>>>18;

  //   ------------------ Section 3 ------------------

  assign typeconvert3 = (a1sum3[30:0] + {a1sum3[15], {14{~a1sum3[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section3
      if (reset == 1'b1) begin
        delay_section3[0] <= 16'b0000000000000000;
        delay_section3[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section3[1] <= delay_section3[0];
          delay_section3[0] <= typeconvert3;
        end
      end
    end // delay_process_section3

  assign inputconv3 = $signed({scaletypeconvert3[15:0], 18'b000000000000000000});

  assign mul_temp_9 = delay_section3[0] * coeff_a2_section3;
  assign a2mul3 = $signed({mul_temp_9[29:0], 1'b0});

  assign mul_temp_10 = delay_section3[1] * coeff_a3_section3;
  assign a3mul3 = $signed({mul_temp_10[29:0], 1'b0});

  assign b1mul3 = $signed({typeconvert3[14:0], 16'b0000000000000000});

  assign mul_temp_11 = delay_section3[0] * coeff_b2_section3;
  assign b2mul3 = $signed({mul_temp_11[28:0], 2'b00});

  assign b3mul3 = $signed({delay_section3[1][14:0], 16'b0000000000000000});

  assign sub_cast_8 = inputconv3;
  assign sub_cast_9 = $signed({{3{a2mul3[30]}}, a2mul3});
  assign sub_temp_4 = sub_cast_8 - sub_cast_9;
  assign a2sum3 = sub_temp_4[33:0];

  assign sub_cast_10 = a2sum3;
  assign sub_cast_11 = $signed({{3{a3mul3[30]}}, a3mul3});
  assign sub_temp_5 = sub_cast_10 - sub_cast_11;
  assign a1sum3 = sub_temp_5[33:0];

  assign b1multypeconvert3 = $signed({{3{b1mul3[30]}}, b1mul3});

  assign add_cast_8 = b1multypeconvert3;
  assign add_cast_9 = $signed({{3{b2mul3[30]}}, b2mul3});
  assign add_temp_4 = add_cast_8 + add_cast_9;
  assign b2sum3 = add_temp_4[33:0];

  assign add_cast_10 = b2sum3;
  assign add_cast_11 = $signed({{3{b3mul3[30]}}, b3mul3});
  assign add_temp_5 = add_cast_10 + add_cast_11;
  assign b1sum3 = add_temp_5[33:0];

  assign section_result3 = (b1sum3[33:0] + {b1sum3[18], {17{~b1sum3[18]}}})>>>18;

  assign mul_temp_12 = section_result3 * scaleconst4;
  assign scale4 = $signed({mul_temp_12[31:0], 2'b00});

  assign scaletypeconvert4 = (scale4[33:0] + {scale4[18], {17{~scale4[18]}}})>>>18;

  //   ------------------ Section 4 ------------------

  assign typeconvert4 = (a1sum4[30:0] + {a1sum4[15], {14{~a1sum4[15]}}})>>>15;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section4
      if (reset == 1'b1) begin
        delay_section4[0] <= 16'b0000000000000000;
        delay_section4[1] <= 16'b0000000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section4[1] <= delay_section4[0];
          delay_section4[0] <= typeconvert4;
        end
      end
    end // delay_process_section4

  assign inputconv4 = $signed({scaletypeconvert4[15:0], 18'b000000000000000000});

  assign mul_temp_13 = delay_section4[0] * coeff_a2_section4;
  assign a2mul4 = $signed({mul_temp_13[29:0], 1'b0});

  assign mul_temp_14 = delay_section4[1] * coeff_a3_section4;
  assign a3mul4 = $signed({mul_temp_14[29:0], 1'b0});

  assign b1mul4 = $signed({typeconvert4[14:0], 16'b0000000000000000});

  assign mul_temp_15 = delay_section4[0] * coeff_b2_section4;
  assign b2mul4 = $signed({mul_temp_15[28:0], 2'b00});

  assign b3mul4 = $signed({delay_section4[1][14:0], 16'b0000000000000000});

  assign sub_cast_12 = inputconv4;
  assign sub_cast_13 = $signed({{3{a2mul4[30]}}, a2mul4});
  assign sub_temp_6 = sub_cast_12 - sub_cast_13;
  assign a2sum4 = sub_temp_6[33:0];

  assign sub_cast_14 = a2sum4;
  assign sub_cast_15 = $signed({{3{a3mul4[30]}}, a3mul4});
  assign sub_temp_7 = sub_cast_14 - sub_cast_15;
  assign a1sum4 = sub_temp_7[33:0];

  assign b1multypeconvert4 = $signed({{3{b1mul4[30]}}, b1mul4});

  assign add_cast_12 = b1multypeconvert4;
  assign add_cast_13 = $signed({{3{b2mul4[30]}}, b2mul4});
  assign add_temp_6 = add_cast_12 + add_cast_13;
  assign b2sum4 = add_temp_6[33:0];

  assign add_cast_14 = b2sum4;
  assign add_cast_15 = $signed({{3{b3mul4[30]}}, b3mul4});
  assign add_temp_7 = add_cast_14 + add_cast_15;
  assign b1sum4 = add_temp_7[33:0];

  assign output_typeconvert = (b1sum4[33:0] + {b1sum4[2], {1{~b1sum4[2]}}})>>>2;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter_assgn_3
